/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ques3.h"


void
program_prog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *get_date_and_time_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAM_PROG, PROGRAM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_date_and_time_1((void*)&get_date_and_time_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Server sent response -> %s", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	program_prog_1 (host);
exit (0);
}
