/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QUES3_H_RPCGEN
#define _QUES3_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROGRAM_PROG 0x12345687
#define PROGRAM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_date_and_time 1
extern  char ** get_date_and_time_1(void *, CLIENT *);
extern  char ** get_date_and_time_1_svc(void *, struct svc_req *);
extern int program_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_date_and_time 1
extern  char ** get_date_and_time_1();
extern  char ** get_date_and_time_1_svc();
extern int program_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QUES3_H_RPCGEN */
