/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <time.h>
#include "ques3.h"

char **
get_date_and_time_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

    printf("Sending current date and time to client\n");

	// char* retval;                                                               
	time_t t = time(NULL);                                                        
	result = ctime(&t);                                                                    
	// result = retval;

	return &result;
}
