/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ques1.h"

#define MAX_MSG_LEN 256

message *
chat_func_1_svc(message *argp, struct svc_req *rqstp)
{
	static message  result;

	/*
	 * insert server code here
	 */
	printf("Client sent message -> %s\n", argp->msg);
	char msg[MAX_MSG_LEN] = "";
	printf("Enter response: ");
	fgets(msg, sizeof(msg), stdin);
	msg[strcspn(msg, "\n")] = 0;
	strcpy(result.msg, msg);

	return &result;
}
