/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ques1.h"

#define MAX_MSG_LEN 256


void
program_prog_1(char *host, char *msg)
{
	CLIENT *clnt;
	message  *result_1;
	message  chat_func_1_arg;
	strcpy(chat_func_1_arg.msg, msg);

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAM_PROG, PROGRAM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = chat_func_1(&chat_func_1_arg, clnt);
	if (result_1 == (message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Server sent response -> %s\n", (*result_1).msg);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	char msg[MAX_MSG_LEN] = "";
	printf("Enter message: ");
	fgets(msg, sizeof(msg), stdin);
	msg[strcspn(msg, "\n")] = 0;
	while (strcmp(msg, "exit") != 0)
	{
		program_prog_1(host, msg);
		printf("Enter message: ");
		fgets(msg, sizeof(msg), stdin);
		msg[strcspn(msg, "\n")] = 0;
	}
exit (0);
}
