/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include "ques2.h"


void
program_prog_1(char *host, int num)
{
	CLIENT *clnt;
	int  *result_1;
	number  factorial_1_arg;
	factorial_1_arg.a = num;

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAM_PROG, PROGRAM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = factorial_1(&factorial_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Factorial of %d = %d\n", num, *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *input;

	if (argc < 3) {
		printf ("usage: %s server_host [NUMBER]\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	input = argv[2];
	program_prog_1 (host, atoi(input));
exit (0);
}
